name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Autenticación con Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: lab-docker-cloud

      - name: Configurar Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build y Push
        run: |
          docker build -t us-central1-docker.pkg.dev/lab-docker-cloud/docker-repo/mi-app-docker .
          docker push us-central1-docker.pkg.dev/lab-docker-cloud/docker-repo/mi-app-docker

      - name: Deploy a Cloud Run
        run: |
          gcloud run deploy mi-app \
            --image us-central1-docker.pkg.dev/lab-docker-cloud/docker-repo/mi-app-docker \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
